server:
  port: 8082


spring:
  application:
    name: app2
  profiles:
    active: db,log,mybatis,swagger


nacos:
  host: 10.100.218.45
  port: 8848
  username: nacos
  password: nacos

dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
    port: -1
  registry:
#    address: nacos://${nacos.host}:${nacos.port}/?username=${nacos.username}&password=${nacos.password}
    address: zookeeper://10.100.218.28:2181

  scan:
    base-packages: io.github.lsyf.app2.dubbo



